# Configuration for a dummy model
"model_type" : "dummy"
model:
  hidden_dim: 128
training:
  learning_rate: 1e-3
  batch_size: 8
  num_epochs: 0
  patience: 0
  algo: "bellman_ford"
  model_name: "dummy"
  dataset: "all"