# Configuration for a tiny GNNInterpNetwork
model_type: "gnn"

model:
  hidden_dim: 128
  proj_dim: 8
  msg_dim: 4
  edge_dim: 4
  gnn_layers: 1
  dropout: 0.1

training:
  learning_rate: 5e-4
  batch_size: 8
  num_epochs: 150
  patience: 4
  algo: "bellman_ford"
  model_name: "gnn_tiny"