# Configuration for a smaller GNNJointInterpNetwork
model_type: "gnn_joint"

model:
  hidden_dim: 128
  proj_dim: 32
  msg_dim: 16
  edge_dim: 4
  gnn_layers: 1
  dropout: 0.1

training:
  scheduler:
    type: "fine_tune"
    schedule: [5, 0]
  learning_rate: 5e-4
  batch_size: 4
  num_epochs: 150
  patience: 4
  algo: "dijkstra_bfs"
  algorithms: ["dijkstra", "bfs"]
  model_name: "gnn_small"