# Configuration for a larger GNNInterpNetwork
model_type: "gnn"

model:
  hidden_dim: 128
  proj_dim: 128
  msg_dim: 32
  gnn_layers: 2
  dropout: 0.1

training:
  learning_rate: 5e-4
  batch_size: 8
  num_epochs: 150
  patience: 5
  algo: "bellman_ford"
  model_name: "gnn_large"