# Configuration for a smaller GNNJointInterpNetwork
model_type: "gnn_joint"

model:
  hidden_dim: 128
  proj_dim: 32
  msg_dim: 16
  gnn_layers: 1
  dropout: 0.1

training:
  learning_rate: 5e-2
  batch_size: 8
  num_epochs: 150
  patience: 5
  algo: "bellman_ford_bfs"
  algorithms: ["bellman_ford", "bfs"]
  model_name: "gnn_small"