model_type: "gnn"

model:
  hidden_dim: 128
  proj_dim: 128
  msg_dim: 8
  edge_dim: 16
  gnn_layers: 3
  dropout: 0.1

training:
  learning_rate: 5e-4
  batch_size: 8
  num_epochs: 150
  patience: 5
  algo: "bellman_ford"
  model_name: "gnn_3_layer_128_8_16"