# Configuration for a InterpNetwork
"model_type" : "mlp_diff"
model:
  hidden_dim: 128
  proj_dim: 128
  dropout: 0.1

training:
  learning_rate: 3e-4
  batch_size: 8
  num_epochs: 100
  patience: 5
  algo: "bellman_ford"
  model_name: "mlp_diff"
  dataset: "all"
